FROM apache/airflow:2.10.5-python3.10
 
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
 
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
 
USER airflow
# pyspark phải cùng version với Spark cluster (3.5.3)
RUN pip install --no-cache-dir \
    pyspark==3.5.3 \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-amazon \
    kafka-python \
    boto3